// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXhVulVKxrf5R4KPvzBupMg2ff9YqhnR4',
    appId: '1:512051262332:android:181a35455de185ec64aaf9',
    messagingSenderId: '512051262332',
    projectId: 'topshelf-aaa-2026',
    databaseURL: 'https://topshelf-aaa-2026-default-rtdb.firebaseio.com',
    storageBucket: 'topshelf-aaa-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ukswKtjMnxqdIXIo14rSqj_urE-VbUQ',
    appId: '1:512051262332:web:92771696dec3873964aaf9',
    messagingSenderId: '512051262332',
    projectId: 'topshelf-aaa-2026',
    authDomain: 'topshelf-aaa-2026.firebaseapp.com',
    databaseURL: 'https://topshelf-aaa-2026-default-rtdb.firebaseio.com',
    storageBucket: 'topshelf-aaa-2026.firebasestorage.app',
  );

}